version: '3'

services:
  til-app:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: testing.dockerfile
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_DB=vapor_test
      - POSTGRES_USER=vapor_username
      - POSTGRES_PASSWORD=vapor_password
